<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../fixtures/**/*.json;../fixtures/**/*.xml;../fixtures/**/*.pdf" LinkBase="fixtures" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Shouldly" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/PaperPilot.Core/PaperPilot.Core.csproj" />
    <ProjectReference Include="../../src/PaperPilot.Infrastructure/PaperPilot.Infrastructure.csproj" />
    <ProjectReference Include="../../src/PaperPilot.Rag/PaperPilot.Rag.csproj" />
    <ProjectReference Include="../../src/PaperPilot.ServiceDefaults/PaperPilot.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
