<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <EmbeddedResource Include="Prompts/*.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PaperPilot.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PaperPilot.Core/PaperPilot.Core.csproj" />
    <ProjectReference Include="../PaperPilot.Infrastructure/PaperPilot.Infrastructure.csproj" />
  </ItemGroup>

</Project>
