// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaperPilot.Infrastructure.Persistence;

#nullable disable

namespace PaperPilot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaperPilotDbContext))]
    [Migration("20261002164432_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaperPilot.Core.Domain.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<string>("ArxivId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arxiv_id");

                    b.PrimitiveCollection<List<string>>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.PrimitiveCollection<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("categories");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("ParserMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("parser_metadata");

                    b.Property<string>("ParserUsed")
                        .HasColumnType("text")
                        .HasColumnName("parser_used");

                    b.Property<bool>("PdfProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("pdf_processed");

                    b.Property<DateTimeOffset?>("PdfProcessingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pdf_processing_date");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<DateTimeOffset>("PublishedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_date");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.PrimitiveCollection<List<string>>("References")
                        .HasColumnType("text[]")
                        .HasColumnName("references");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Sections", "PaperPilot.Core.Domain.Paper.Sections#PaperSection", b1 =>
                        {
                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasJsonPropertyName("content");

                            b1.Property<int>("Level")
                                .HasJsonPropertyName("level");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasJsonPropertyName("title");

                            b1
                                .ToJson("sections")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id")
                        .HasName("pk_papers");

                    b.HasIndex("ArxivId")
                        .IsUnique()
                        .HasDatabaseName("ix_papers_arxiv_id");

                    b.ToTable("papers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
