<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PaperPilot.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../PaperPilot.ServiceDefaults/PaperPilot.ServiceDefaults.csproj" />
    <ProjectReference Include="../PaperPilot.Core/PaperPilot.Core.csproj" />
    <ProjectReference Include="../PaperPilot.Infrastructure/PaperPilot.Infrastructure.csproj" />
    <ProjectReference Include="../PaperPilot.Rag/PaperPilot.Rag.csproj" />
  </ItemGroup>

</Project>
